# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
minimal_mistakes_skin    : "mint" # Professional and clean look

# Site Settings
locale                   : "en-US"
title                    : "Terry Moore's Portfolio"
title_separator          : "-"
subtitle                 : "Business Major & Computer Science Minor at Georgia Tech"
name                     : "Terry Moore"
description              : "Welcome to my personal website showcasing my projects, skills, and experiences."
url                      : "http://terrymoorev.github.io"
repository               : "terrymoorev/terrymoorev.github.io"
masthead_title           : " "

# Author
author:
  name             : "Terry Moore"
  avatar           : "/assets/images/BIO_Pic.JPG"
  bio              : "I am a second-year student at Georgia Tech majoring in Business and minoring in Computer Science and FinTech. Passionate about technology, project management, and data analytics."
  location         : "Atlanta, GA"
  email            : "Terry.l.moore@gatech.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:terry.l.moore@gatech.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/terrymoorev"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/terrymoore"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Social Sharing
social:
  type                   : "Person"
  name                   : "Terry Moore"
  links:
    - "https://github.com/terrymoorev"
    - "https://linkedin.com/in/terrymoore"
    - "mailto:terry.l.moore@gatech.edu"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/terrymoorev"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/terrymoore"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:terry.l.moore@gatech.edu"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/

# Output
permalink: /:categories/:title/

# Markdown
markdown: kramdown
highlighter: rouge

# Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
