title: "Terry Moore"
author: "Terry Moore"
description: "Georgia Tech"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Theme and Colors
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
header_background: "#003057"      # GT Navy
header_text_color: "#F7E9A7"      # Old Gold
accent_color: "#F7E9A7"
link_color: "#F7E9A7"
link_hover_color: "#DAA520"      # Darker Gold

# Layout
show_excerpts: false       # show article excerpts on the home page
enable_copy_code_button: false
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Navigation
navigation:
  - file: "index.html"
    title: "Home"
    icon: home
  - file: "TerryMooreResume"
    title: "CV"
    icon: file-alt
  - file: "projects.html"
    title: "Projects"
    icon: folder-open
  - file: "coursework.html"
    title: "Coursework"
    icon: book

# External Links (Footer)
external:
  - title: Mail
    icon: envelope
    url: "mailto:terry.l.moore@gatech.edu"
  - title: GitHub
    icon: github
    url: "https://github.com/TerryMooreV"
  - title: Subscribe
    icon: rss
    url: "/feed.xml"

# Comments
# disqus_shortname: ""
# isso_domain: ""

# Plugins
plugins:
  - jekyll-feed
